from __future__ import annotations

DEFAULT_XAU_CATEGORY = "黄金价格"
DEFAULT_FX_CATEGORY = "汇率"
DEFAULT_US_DEBT_CATEGORY = "债务 / 财政"
DEFAULT_STOCK_VOLATILITY_CATEGORY = "股票波动率"

INDICATOR_DEFINITIONS: dict[str, str] = {
    "CPIAUCSL": "美国城市消费者价格指数，衡量居民消费端的整体通胀水平。",
    "CPILFESL": "剔除食品和能源后的核心消费者价格指数，用于观察更平滑的核心通胀趋势。",
    "PCEPI": "个人消费支出价格指数，美联储更常参考的总体通胀指标。",
    "PCEPILFE": "剔除食品和能源后的核心PCE价格指数，用于刻画核心通胀压力。",
    "PPIACO": "全部商品生产者价格指数，反映上游出厂价格变化。",
    "GDPDEF": "GDP平减指数，反映宏观经济整体价格水平的季度变化。",
    "MICH": "密歇根大学消费者1年通胀预期调查，衡量居民短期通胀预期。",
    "T5YIE": "5年盈亏平衡通胀率，近似市场隐含的5年期平均通胀预期。",
    "T10YIE": "10年盈亏平衡通胀率，近似市场隐含的10年期平均通胀预期。",
    "T5YIFR": "5年期5年期前瞻通胀补偿，反映中长期通胀预期。",
    "FEDFUNDS": "联邦基金利率，有效代表美国短端政策利率环境。",
    "SOFR": "担保隔夜融资利率，美国美元无风险短端利率基准之一。",
    "TB3MS": "3个月期美国国债收益率，代表短端无风险名义利率。",
    "DGS10": "10年期美国国债收益率，代表长期名义利率水平。",
    "DFII5": "5年期TIPS实际收益率，代表中短端实际利率水平。",
    "DFII10": "10年期TIPS实际收益率，代表长期实际利率水平。",
    "DFII30": "30年期TIPS实际收益率，代表超长端实际利率水平。",
    "DTWEXBGS": "美元广义贸易加权指数，衡量美元相对主要贸易伙伴货币的强弱。",
    "DXY": "ICE U.S. Dollar Index，衡量美元相对一篮子主要货币的强弱。",
    "EURUSD": "EUR/USD，欧元兑美元，全球交易量最大的货币对之一。",
    "GBPUSD": "GBP/USD，英镑兑美元。",
    "USDJPY": "USD/JPY，美元兑日元。",
    "AUDUSD": "AUD/USD，澳元兑美元。",
    "USDCAD": "USD/CAD，美元兑加元。",
    "USDCHF": "USD/CHF，美元兑瑞士法郎。",
    "M1SL": "美国M1货币供应量，反映高流动性狭义货币规模。",
    "M2SL": "美国M2货币供应量，反映广义货币条件。",
    "BOGMBASE": "美国货币基础，衡量央行基础货币投放规模。",
    "PAYEMS": "美国非农就业人数，反映劳动力市场扩张或收缩。",
    "UNRATE": "美国失业率，反映劳动力市场松紧程度。",
    "BAMLC0A0CM": "ICE BofA美国投资级企业债OAS，衡量投资级信用利差。",
    "BAMLH0A0HYM2": "ICE BofA美国高收益企业债OAS，衡量高收益信用风险溢价。",
    "TEDRATE": "TED利差，反映银行间融资风险与流动性压力。",
    "STLFSI4": "圣路易斯联储金融压力指数，综合刻画金融市场紧张程度。",
    "DCOILWTICO": "WTI原油现货价格，用于跟踪能源价格和通胀传导。",
    "DCOILBRENTEU": "Brent原油现货价格，用于跟踪全球能源价格变化。",
    "PCOPPUSDM": "铜价，用于刻画工业需求和全球增长预期。",
    "DERIVED__10年期通胀预期_名义减实际": "10年期美债收益率减去10年期TIPS实际收益率，近似长期通胀预期。",
    "GVZ": "Cboe Gold ETF Volatility Index，基于GLD期权定价构造的30天黄金隐含波动率指数。",
    "VIX": "Cboe Volatility Index，衡量标普500期权隐含的未来30天年化波动率预期，常被视为美股恐慌指数。",
    "VIX1D": "Cboe 1-Day Volatility Index，衡量标普500期权隐含的未来1个交易日波动率预期。",
    "VIX9D": "Cboe 9-Day Volatility Index，衡量标普500期权隐含的未来9天波动率预期。",
    "VIX3M": "Cboe 3-Month Volatility Index，衡量标普500期权隐含的未来3个月波动率预期。",
    "VIX6M": "Cboe 6-Month Volatility Index，衡量标普500期权隐含的未来6个月波动率预期。",
    "VIX1Y": "Cboe 1-Year Volatility Index，衡量标普500期权隐含的未来1年波动率预期。",
    "VXN": "Cboe NASDAQ-100 Volatility Index，衡量纳斯达克100指数期权隐含的未来30天波动率预期。",
    "VVIX": "Cboe VVIX Index，衡量VIX期权所隐含的未来30天VIX波动率，即波动率的波动率。",
    "SKEW": "Cboe SKEW Index，用于衡量标普500收益分布左尾尾部风险的定价水平和崩盘保护需求。",
    "XAU_USD_DAILY_OHLC": "XAU/USD黄金兑美元日线OHLC价格序列，适合构造收益率、波动率和技术特征。",
    "XAU_USD_MONTHLY_CLOSE": "XAU/USD黄金兑美元月度收盘价序列，适合月频对齐和中长期建模。",
    "GLOBAL_GOLD_ETF_HOLDINGS_WEEKLY": "World Gold Council全球实物黄金ETF总持仓周度序列，单位为吨。",
    "GLOBAL_GOLD_ETF_HOLDINGS_MONTHLY": "World Gold Council全球实物黄金ETF总持仓月度序列，单位为吨。",
    "GLOBAL_GOLD_ETF_NET_FLOWS_WEEKLY": "World Gold Council全球实物黄金ETF净流量周度序列，按吨衡量净流入和净流出。",
    "GLOBAL_GOLD_ETF_NET_FLOWS_MONTHLY": "World Gold Council全球实物黄金ETF净流量月度序列，按吨衡量净流入和净流出。",
    "GLD_TOTAL_HOLDINGS_TONNES": "SPDR Gold Shares (GLD) 信托持有黄金总量，单位为吨。",
    "GLD_DAILY_SHARE_VOLUME": "SPDR Gold Shares (GLD) 每日成交量，单位为股。",
    "GLOBAL_GOLD_MINE_PRODUCTION_QUARTERLY": "World Gold Council全球矿产金产量季度序列，单位为吨。",
    "GLOBAL_GOLD_MINE_PRODUCTION_ANNUAL": "World Gold Council全球矿产金产量年度序列，单位为吨。",
    "GLOBAL_GOLD_CASH_COST_QUARTERLY": "全球黄金矿业平均现金成本季度序列，目标口径为美元/盎司；当前仓库保留为待接入指标。",
    "GLOBAL_GOLD_CASH_COST_ANNUAL": "全球黄金矿业平均现金成本年度序列，目标口径为美元/盎司；当前仓库保留为待接入指标。",
    "GLOBAL_GOLD_AISC_QUARTERLY": "World Gold Council全球黄金矿业平均全维持成本（AISC）季度序列，单位为美元/盎司。",
    "GLOBAL_GOLD_AISC_ANNUAL": "基于World Gold Council季度AISC序列汇总得到的年度平均全维持成本，单位为美元/盎司。",
    "GFDEBTN": "Total federal debt from FRED, covering debt held by the public and intragovernmental holdings.",
    "FYGFDPUN": "Federal debt held by the public from FRED, representing the portion absorbed by the market.",
    "GFDEGDQ188S": "Total federal debt as a share of GDP from FRED.",
    "FYGFGDQ188S": "Federal debt held by the public as a share of GDP from FRED.",
    "FYFSD": "Federal surplus or deficit from FRED; negative values indicate a deficit.",
    "FYFSGDA188S": "Federal surplus or deficit as a share of GDP from FRED.",
    "A091RC1Q027SBEA": "Federal government interest payments from BEA via FRED, quarterly.",
    "GDP": "Nominal gross domestic product from FRED, quarterly seasonally adjusted annual rate.",
    "W018RC1Q027SBEA": "Federal current receipts from BEA via FRED, quarterly seasonally adjusted annual rate.",
    "DERIVED__Federal Interest Payments to GDP": "Federal interest payments divided by nominal GDP, expressed as a percent.",
    "DERIVED__Federal Interest Payments to Receipts": "Federal interest payments divided by federal current receipts, expressed as a percent.",
    "FEDERAL_DEBT_INTRAGOVERNMENTAL_HOLDINGS": "Intragovernmental holdings from Treasury Debt to the Penny, expressed in millions of dollars.",
    "MARKETABLE_TREASURY_SECURITIES_OUTSTANDING": "Total marketable Treasury securities outstanding from the Monthly Statement of the Public Debt, expressed in millions of dollars.",
    "TREASURY_NET_MARKETABLE_BORROWING_ESTIMATE": "Treasury quarterly financing estimate series built from official Financing Estimates releases, with value equal to the current-quarter net marketable borrowing estimate in billions of dollars.",
    "AVERAGE_INTEREST_RATE_ON_TOTAL_INTEREST_BEARING_DEBT": "Average interest rate on total interest-bearing debt from Treasury Fiscal Data, monthly percent.",
}

XAU_INDICATORS: tuple[dict[str, str], ...] = (
    {
        "indicator_id": "XAU_USD_DAILY_OHLC",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "XAU/USD日线OHLC",
        "chinese_name": "XAU/USD日线OHLC",
        "english_code": "XAU_USD_DAILY_OHLC",
        "source": "huggingface+investing",
        "frequency": "d",
        "file_name": "xau_usd_daily_ohlc.csv",
    },
    {
        "indicator_id": "XAU_USD_MONTHLY_CLOSE",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "XAU/USD月度收盘价",
        "chinese_name": "XAU/USD月度收盘价",
        "english_code": "XAU_USD_MONTHLY_CLOSE",
        "source": "macrotrends",
        "frequency": "m",
        "file_name": "xau_usd_monthly_close.csv",
    },
    {
        "indicator_id": "GVZ",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "GVZ",
        "chinese_name": "Cboe黄金ETF波动率指数",
        "english_code": "GVZ",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "GVZ.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_ETF_HOLDINGS_WEEKLY",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold ETF Holdings (Weekly)",
        "chinese_name": "全球黄金ETF总持仓（周度）",
        "english_code": "GLOBAL_GOLD_ETF_HOLDINGS_WEEKLY",
        "source": "wgc_fsapi",
        "frequency": "w",
        "file_name": "global_gold_etf_holdings_weekly.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_ETF_HOLDINGS_MONTHLY",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold ETF Holdings (Monthly)",
        "chinese_name": "全球黄金ETF总持仓（月度）",
        "english_code": "GLOBAL_GOLD_ETF_HOLDINGS_MONTHLY",
        "source": "wgc_fsapi",
        "frequency": "m",
        "file_name": "global_gold_etf_holdings_monthly.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_ETF_NET_FLOWS_WEEKLY",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold ETF Net Flows (Weekly)",
        "chinese_name": "全球黄金ETF净流量（周度）",
        "english_code": "GLOBAL_GOLD_ETF_NET_FLOWS_WEEKLY",
        "source": "wgc_fsapi",
        "frequency": "w",
        "file_name": "global_gold_etf_net_flows_weekly.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_ETF_NET_FLOWS_MONTHLY",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold ETF Net Flows (Monthly)",
        "chinese_name": "全球黄金ETF净流量（月度）",
        "english_code": "GLOBAL_GOLD_ETF_NET_FLOWS_MONTHLY",
        "source": "wgc_fsapi",
        "frequency": "m",
        "file_name": "global_gold_etf_net_flows_monthly.csv",
    },
    {
        "indicator_id": "GLD_TOTAL_HOLDINGS_TONNES",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "GLD Total Gold Holdings",
        "chinese_name": "GLD总持仓量",
        "english_code": "GLD_TOTAL_HOLDINGS_TONNES",
        "source": "spdr_api",
        "frequency": "d",
        "file_name": "GLD_total_holdings_tonnes.csv",
    },
    {
        "indicator_id": "GLD_DAILY_SHARE_VOLUME",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "GLD Daily Share Volume",
        "chinese_name": "GLD成交量",
        "english_code": "GLD_DAILY_SHARE_VOLUME",
        "source": "spdr_api",
        "frequency": "d",
        "file_name": "GLD_share_volume.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_MINE_PRODUCTION_QUARTERLY",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold Mine Production (Quarterly)",
        "chinese_name": "全球矿产金产量（季度）",
        "english_code": "GLOBAL_GOLD_MINE_PRODUCTION_QUARTERLY",
        "source": "wgc_fsapi",
        "frequency": "q",
        "file_name": "global_gold_mine_production_quarterly.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_MINE_PRODUCTION_ANNUAL",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold Mine Production (Annual)",
        "chinese_name": "全球矿产金产量（年度）",
        "english_code": "GLOBAL_GOLD_MINE_PRODUCTION_ANNUAL",
        "source": "wgc_fsapi",
        "frequency": "A",
        "file_name": "global_gold_mine_production_annual.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_AISC_QUARTERLY",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold AISC (Quarterly)",
        "chinese_name": "全球黄金全维持成本（季度）",
        "english_code": "GLOBAL_GOLD_AISC_QUARTERLY",
        "source": "wgc_fsapi",
        "frequency": "q",
        "file_name": "global_gold_aisc_quarterly.csv",
    },
    {
        "indicator_id": "GLOBAL_GOLD_AISC_ANNUAL",
        "category": DEFAULT_XAU_CATEGORY,
        "indicator_name": "Global Gold AISC (Annual)",
        "chinese_name": "全球黄金全维持成本（年度）",
        "english_code": "GLOBAL_GOLD_AISC_ANNUAL",
        "source": "wgc_fsapi+derived",
        "frequency": "A",
        "file_name": "global_gold_aisc_annual.csv",
    },
)

FX_INDICATORS: tuple[dict[str, str], ...] = (
    {
        "indicator_id": "DXY",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "DXY",
        "chinese_name": "美元指数",
        "english_code": "DXY",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "DXY.csv",
    },
    {
        "indicator_id": "EURUSD",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "EURUSD",
        "chinese_name": "欧元/美元",
        "english_code": "EURUSD",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "EURUSD.csv",
    },
    {
        "indicator_id": "GBPUSD",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "GBPUSD",
        "chinese_name": "英镑/美元",
        "english_code": "GBPUSD",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "GBPUSD.csv",
    },
    {
        "indicator_id": "USDJPY",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "USDJPY",
        "chinese_name": "美元/日元",
        "english_code": "USDJPY",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "USDJPY.csv",
    },
    {
        "indicator_id": "AUDUSD",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "AUDUSD",
        "chinese_name": "澳元/美元",
        "english_code": "AUDUSD",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "AUDUSD.csv",
    },
    {
        "indicator_id": "USDCAD",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "USDCAD",
        "chinese_name": "美元/加元",
        "english_code": "USDCAD",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "USDCAD.csv",
    },
    {
        "indicator_id": "USDCHF",
        "category": DEFAULT_FX_CATEGORY,
        "indicator_name": "USDCHF",
        "chinese_name": "美元/瑞士法郎",
        "english_code": "USDCHF",
        "source": "yahoo",
        "frequency": "d",
        "file_name": "USDCHF.csv",
    },
)

US_DEBT_INDICATORS: tuple[dict[str, str], ...] = (
    {
        "indicator_id": "FEDERAL_DEBT_INTRAGOVERNMENTAL_HOLDINGS",
        "category": DEFAULT_US_DEBT_CATEGORY,
        "indicator_name": "Federal Debt Intragovernmental Holdings",
        "chinese_name": "政府内部持有债务",
        "english_code": "FEDERAL_DEBT_INTRAGOVERNMENTAL_HOLDINGS",
        "source": "treasury_fiscal_data",
        "frequency": "d",
        "file_name": "Federal Debt Intragovernmental Holdings.csv",
    },
    {
        "indicator_id": "MARKETABLE_TREASURY_SECURITIES_OUTSTANDING",
        "category": DEFAULT_US_DEBT_CATEGORY,
        "indicator_name": "Marketable Treasury Securities Outstanding",
        "chinese_name": "可流通国债余额",
        "english_code": "MARKETABLE_TREASURY_SECURITIES_OUTSTANDING",
        "source": "treasury_fiscal_data",
        "frequency": "m",
        "file_name": "Marketable Treasury Securities Outstanding.csv",
    },
    {
        "indicator_id": "TREASURY_NET_MARKETABLE_BORROWING_ESTIMATE",
        "category": DEFAULT_US_DEBT_CATEGORY,
        "indicator_name": "Treasury Net Marketable Borrowing Estimate",
        "chinese_name": "净融资需求",
        "english_code": "TREASURY_NET_MARKETABLE_BORROWING_ESTIMATE",
        "source": "treasury_quarterly_refunding",
        "frequency": "q",
        "file_name": "Treasury Net Marketable Borrowing Estimate.csv",
    },
    {
        "indicator_id": "AVERAGE_INTEREST_RATE_ON_TOTAL_INTEREST_BEARING_DEBT",
        "category": DEFAULT_US_DEBT_CATEGORY,
        "indicator_name": "Average Interest Rate on Total Interest-Bearing Debt",
        "chinese_name": "平均付息成本",
        "english_code": "AVERAGE_INTEREST_RATE_ON_TOTAL_INTEREST_BEARING_DEBT",
        "source": "treasury_fiscal_data",
        "frequency": "m",
        "file_name": "Average Interest Rate on Total Interest-Bearing Debt.csv",
    },
)

STOCK_VOLATILITY_INDICATORS: tuple[dict[str, str], ...] = (
    {
        "indicator_id": "VIX",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VIX",
        "chinese_name": "",
        "english_code": "VIX",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VIX.csv",
    },
    {
        "indicator_id": "VIX1D",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VIX1D",
        "chinese_name": "",
        "english_code": "VIX1D",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VIX1D.csv",
    },
    {
        "indicator_id": "VIX9D",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VIX9D",
        "chinese_name": "",
        "english_code": "VIX9D",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VIX9D.csv",
    },
    {
        "indicator_id": "VIX3M",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VIX3M",
        "chinese_name": "",
        "english_code": "VIX3M",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VIX3M.csv",
    },
    {
        "indicator_id": "VIX6M",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VIX6M",
        "chinese_name": "",
        "english_code": "VIX6M",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VIX6M.csv",
    },
    {
        "indicator_id": "VIX1Y",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VIX1Y",
        "chinese_name": "",
        "english_code": "VIX1Y",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VIX1Y.csv",
    },
    {
        "indicator_id": "VXN",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VXN",
        "chinese_name": "",
        "english_code": "VXN",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VXN.csv",
    },
    {
        "indicator_id": "VVIX",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "VVIX",
        "chinese_name": "",
        "english_code": "VVIX",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "VVIX.csv",
    },
    {
        "indicator_id": "SKEW",
        "category": DEFAULT_STOCK_VOLATILITY_CATEGORY,
        "indicator_name": "SKEW",
        "chinese_name": "",
        "english_code": "SKEW",
        "source": "cboe+yahoo",
        "frequency": "d",
        "file_name": "SKEW.csv",
    },
)
